name = "meetup-scrapper"
main = "src/index.ts"
compatibility_date = "2023-10-02"

vars = { TIMEZONE_NAME = "EST" }

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "MEETUP_SCRAPPER_KV"
id = "0000"
